/*
 * rttelemetry.h
 *
 *  Created on: Apr 12, 2024
 *      Author: g0kla
 */

#ifndef RTTELEMETRY_H_
#define RTTELEMETRY_H_

/**
 * This structure is generated by the python gen_header.py script from a csv file.  Change the layout in that tool
 * and re-generate this structure
 */

#ifndef AREX_GW_RADIO
/* This is the ISS layout */

typedef struct __attribute__((__packed__)) {
    unsigned int timestamp : 32;
    unsigned int Mode : 8;
    unsigned int StatusPeriod : 16;
    unsigned int TimePeriod : 16;
    unsigned int TelemPeriod : 16;
    unsigned int WodPeriod : 16;
    unsigned int LogLevel : 8;
    unsigned int SdDriveUse : 8;
    unsigned int CmdKey : 8;
    unsigned int SchedEntries : 8;
    unsigned int CrewModePeriod : 16;
    unsigned int UsbDriveUse : 8;
    unsigned int IHUTemp : 16;
    unsigned int IHUProcSpeed : 8;
    unsigned int CpuResets : 16;
    unsigned int ControlResets : 16;
    unsigned int ResetReason : 8;
    unsigned int SHTC3_temp : 16;
    unsigned int SHTC3_humidity : 16;
    unsigned int LPS22_pressure : 32;
    unsigned int LPS22_temp : 16;
    unsigned int BatteryV : 16;
    unsigned int BatteryI : 16;
    unsigned int AccelerationX : 16;
    unsigned int AccelerationY : 16;
    unsigned int AccelerationZ : 16;
    unsigned int GyroX : 16;
    unsigned int GyroY : 16;
    unsigned int GyroZ : 16;
    unsigned int MagX : 16;
    unsigned int MagY : 16;
    unsigned int MagZ : 16;
    unsigned int IMU_temp : 16;
    unsigned int RadioChannels : 8;
} rttelemetry_t;



#else
typedef struct __attribute__((__packed__)) {
    unsigned int timestamp : 32;
    unsigned int Mode : 8;
    unsigned int RadioTemp : 16;
    unsigned int AntSelected : 8;
    unsigned int AntMode : 8;
    unsigned int RSSI1 : 8;
    unsigned int RSSI2 : 8;
    unsigned int RSSI3 : 8;
    unsigned int RSSI4 : 8;
    unsigned int RSSI5 : 8;
    unsigned int RSSI6 : 8;
    unsigned int pad1 : 8;
    unsigned int IHUTemp : 16;
    unsigned int IHUProcSpeed : 8;
    unsigned int CpuResets : 16;
    unsigned int ControlResets : 16;
    unsigned int ResetReason : 8;
    unsigned int SHTC3_temp : 16;
    unsigned int SHTC3_humidity : 16;
    unsigned int LPS22_pressure : 32;
    unsigned int LPS22_temp : 16;
    unsigned int BatteryV : 16;
    unsigned int BatteryI : 16;
    unsigned int AccelerationX : 16;
    unsigned int AccelerationY : 16;
    unsigned int AccelerationZ : 16;
    unsigned int GyroX : 16;
    unsigned int GyroY : 16;
    unsigned int GyroZ : 16;
    unsigned int MagX : 16;
    unsigned int MagY : 16;
    unsigned int MagZ : 16;
    unsigned int IMU_temp : 16;
    unsigned int pad362 : 8;
} rttelemetry_t;

#endif

//typedef struct __attribute__((__packed__)) {
//	duv_header_t header;
//	exptelemetry_t payload;
//} exp_packet_t;


#endif /* RTTELEMETRY_H_ */
