/*
 * sensor_telemetry.h
 *
 *  Created on: 1 MAY 2025
 *      Author: Chris Thompson, VE2TCP
 */

#ifndef SENSOR_TELEMETRY_H_
#define SENSOR_TELEMETRY_H_

/**
 * This structure is generated by the python gen_header.py script from a csv file.  Change the layout in that tool
 * and re-generate this structure
 */

typedef struct __attribute__((__packed__)) {
    unsigned int timestamp : 32;
    unsigned int LPS22_pressure : 32;
    unsigned int LPS22_temp : 16;
    unsigned int O2_conc : 16;
    unsigned int CO2_conc : 16;
    unsigned int methane_conc : 16;
    unsigned int air_quality : 16;
    unsigned int SHTC3_temp : 16;
    unsigned int SHTC3_humidity : 16;
    unsigned int AccelerationX : 16;
    unsigned int AccelerationY : 16;
    unsigned int AccelerationZ : 16;
    unsigned int GyroX : 16;
    unsigned int GyroY : 16;
    unsigned int GyroZ : 16;
    unsigned int MagX : 16;
    unsigned int MagY : 16;
    unsigned int MagZ : 16;
    unsigned int IHUTemp : 16;
    unsigned int top_count : 16;
    unsigned int bottom_count : 16;
    unsigned int coincident_count : 16;
    unsigned int pi_bus_v : 16;
    unsigned int light_level : 8;
    unsigned int max_sound_level : 8;
    unsigned int light_RGB : 32;
    unsigned int max_sound_bin : 8;
    unsigned char sound_psd[32];
    unsigned int co2_sensor_valid : 1;
    unsigned int o2_sensor_valid : 1;
    unsigned int methane_sensor_valid : 1;
    unsigned int air_q_sensor_valid : 1;
    unsigned int cosmic_watch_valid : 1;
    unsigned int microphone_valid : 1;
    unsigned int waveshare_valid : 1;
    unsigned int pad1 : 1;
} sensor_telemetry_t;


#endif /* SENSOR_TELEMETRY_H_ */
